-- Seed data for booking_amenities table
-- NOTE: Booking amenities cannot be seeded until bookings exist
-- This file is commented out until bookings are created
--
-- Example structure (requires booking_id from bookings table):
-- INSERT INTO booking_amenities (booking_id, amenity_id) VALUES
--   ((SELECT booking_id FROM bookings WHERE booking_user_id = (SELECT user_id FROM users WHERE user_email = 'user@example.com') LIMIT 1),
--    (SELECT amenity_id FROM amenities WHERE amenity_name = 'Projector')),
--   ((SELECT booking_id FROM bookings WHERE booking_user_id = (SELECT user_id FROM users WHERE user_email = 'user@example.com') LIMIT 1),
--    (SELECT amenity_id FROM amenities WHERE amenity_name = 'WiFi'));

