-- Seed data for bookings table
-- NOTE: Bookings cannot be seeded until users exist in auth.users and public.users
-- Users must be created via Supabase Auth Admin API first
-- This file is commented out until users are created
--
-- Example structure (requires user_id from auth.users):
-- INSERT INTO bookings (
--   booking_user_id,
--   booking_meeting_room_id,
--   booking_start_time,
--   booking_end_time,
--   booking_date,
--   booking_is_type_of_booking,
--   booking_number_of_people,
--   booking_total_price,
--   booking_discount,
--   booking_payment_status
-- ) VALUES
--   ((SELECT user_id FROM users WHERE user_email = 'user@example.com'), 
--    (SELECT meeting_room_id FROM meeting_rooms WHERE meeting_room_name = 'Room of Innovation'),
--    '2024-12-10 09:00:00+00', '2024-12-10 10:00:00+00', '2024-12-10', 'booking', 8, 50.00, 0.00, 'paid');

