-- Seed data for users table
-- NOTE: Users must be created via Supabase Auth first (by admins)
-- This seed file is for reference only. Users are created through the admin interface
-- which creates both the auth.users entry and the public.users entry.
--
-- Example structure (DO NOT RUN - users must exist in auth.users first):
-- INSERT INTO users (user_id, user_username, user_email, user_role_id, user_subscription_id, user_current_monthly_bookings) 
-- VALUES 
--   ('<auth.users.id>', 'admin_user', 'admin@example.com', '<role_id>', '<subscription_id>', 0);
--
-- To seed users:
-- 1. Create user via Supabase Auth Admin API (gets auth.users.id)
-- 2. Insert into public.users using that auth.users.id

